#version 450
#define FREQ 6.28

layout(std430, push_constant) uniform pushConstants {
    uint flockSize;
};

layout(std430, binding = 0) buffer posInSSBO {
    vec3 posIn[];
};

layout(std430, binding = 1) buffer velInSSBO {
    vec3 velIn[];
};

layout (local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

uint pcg_hash(uint x)
{
    uint state = x * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float castRescale(uint x)
{

    return 2.0 * (float(x) / 4294967296.0) - 1.0;
}

void main()
{

    uint index = gl_GlobalInvocationID.x;

    if (index >= flockSize)
        return;

    uint u1 = pcg_hash(index);
    uint u2 = pcg_hash(u1);
    uint u3 = pcg_hash(u2);

    posIn[index] = vec3(castRescale(u1), castRescale(u2), castRescale(u3));

    u1 = pcg_hash(u3);
    u2 = pcg_hash(u1);
    u3 = pcg_hash(u2);

    velIn[index] = vec3(castRescale(u1), castRescale(u2), castRescale(u3));
}
